name: Manual Audit
on:
  workflow_dispatch:
    inputs:
      pnpm-version:
        description: 'The version of pnpm to use'
        required: true
        default: 7
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
