name: Audit Dependencies
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.8.0
      - uses: actions/setup-node@v3
      - run: |
          pnpm audit
