name: Audit Dependencies
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.8.0
          run_install: false
      - uses: actions/setup-node@v3
      - name: run the audit
        run: ./run-audit.sh
        env:
          GH_TOKEN: ${{ github.token }}
