name: Audit Dependencies
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.8.0
      - uses: actions/setup-node@v3
      - run: |
          # run pnpm audit and determine if there are errors
          pnpm audit --json | tee audit.json
          COUNT=$(cat audit.json | jq -r '.metadata.vulnerabilities | .high')
          
          if [[ $COUNT -gt 0 ]]; then
            echo "There are $COUNT high vulnerabilities"
            exit 1
          fi
          
