name: Weekly Audit
on:
  schedule:
    - cron: '0 0 * * *' # once a week
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
      - uses: ./
