name: Weekly Audit Dependencies
on:
schedule:
  - cron: '0 0 * * *' # once a week
workflow_dispatch:
  inputs:
    - name: 'VERSION'
      description: '`pnpm` version'
      default: 7
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ github.event.inputs.VERSION }}
          run_install: false
      - uses: actions/setup-node@v3
      - name: run the audit
        run: ./run-audit.sh
        env:
          GH_TOKEN: ${{ github.token }}
